# SPDX-FileCopyrightText: Copyright (c) 2023 - 2024 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Defaults
defaults:
  - regression

# Minimal training config with frequent printouts and checkpoint saving.
# Can be used to test that training runs without errors.
# Do not use for real training runs.

training:
  print_progress_freq: 5 # How often to print progress, measured in number of training steps
  checkpoint_freq: 5 # How often to save the checkpoints, measured in number of training steps
  validation_freq: 5 # how often to record the validation loss, measured in number of training steps
  batch_size: 2
  total_train_steps: 20
